language: c

compiler:
  - gcc
  - clang

env:
  global:
    - CFLAGS="-Wall -O2"
  matrix:
    - VULKAN_VERSION="1.0.8.0"  VULKAN_ARCH="x86_64" GDRIVE_ID="0B7gFCFodR4vpOVBpelZORnNISVU"
    - VULKAN_VERSION="1.0.17.0" VULKAN_ARCH="x86_64" GDRIVE_ID="0B7gFCFodR4vpTkxjMzB3TG9YaTA"

before_script:
  - wget "www.googledrive.com/host/$GDRIVE_ID"
  - mv "$GDRIVE_ID" "vulkansdk-linux-$VULKAN_ARCH-$VULKAN_VERSION"
  - chmod +x "vulkansdk-linux-$VULKAN_ARCH-$VULKAN_VERSION"
  - ./"vulkansdk-linux-$VULKAN_ARCH-$VULKAN_VERSION"
  - mkdir m4 || true
  - autoreconf -i

script:
  - VULKAN_SDK="$(pwd)/VulkanSDK/$VULKAN_VERSION/$VULKAN_ARCH" ./configure
  - make

notifications:
  email: false
